#!/usr/bin/env python3
import os
import sys

inp = sys.argv[1]
out = sys.argv[2]
name = sys.argv[3]
data = open(inp, 'rb').read()
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out + '.h', 'w') as f:
    guard = name.upper() + '_H'
    f.write('/* Auto-generated by tools/bin2c.py. Do not edit. */\n')
    f.write('#ifndef %s\n#define %s\n' % (guard, guard))
    f.write('extern const unsigned char %s[%d];\n' % (name, len(data)))
    f.write('extern const unsigned int %s_len;\n' % name)
    f.write('#endif\n')
with open(out + '.c', 'w') as f:
    f.write('/* Auto-generated by tools/bin2c.py. Do not edit. */\n')
    f.write('#include "%s.h"\n\n' % os.path.basename(out))
    f.write('const unsigned char %s[%d] = {\n' % (name, len(data)))
    for i in range(0, len(data), 16):
        f.write('  ' + ','.join(str(b) for b in data[i:i+16]) + ',\n')
    f.write('};\n')
    f.write('const unsigned int %s_len = %d;\n' % (name, len(data)))
print('%s: %d bytes' % (name, len(data)))
