#!/usr/bin/env python3
"""Convert Doom MUS lumps into a tiny Genesis music event stream.

The generated stream is intentionally simple so it can be consumed by a small
Z80 driver. Each event stores a 16-bit little-endian delay in MUS ticks
(140 Hz), then an opcode. YM2612. MUS channel 15 is kept as a compact FM drum event on channel 5.
"""
import os
import struct
import sys

WAD = sys.argv[1] if len(sys.argv) > 1 else "wad/doom1.wad"
OUT = sys.argv[2] if len(sys.argv) > 2 else "port/gen/music_gen"
LUMP = sys.argv[3] if len(sys.argv) > 3 else "D_E1M1"


def read_lump(path, name):
    d = open(path, "rb").read()
    magic, num, off = struct.unpack("<4sii", d[:12])
    if magic not in (b"IWAD", b"PWAD"):
        raise SystemExit("not a WAD: %r" % (magic,))
    for i in range(num):
        e = d[off + i * 16:off + i * 16 + 16]
        fp, sz = struct.unpack("<ii", e[:8])
        nm = e[8:16].split(b"\0")[0].decode("latin1")
        if nm == name:
            return d[fp:fp + sz]
    raise SystemExit("lump not found: %s" % name)


def read_var(mus, pos):
    value = 0
    shift = 0
    while True:
        b = mus[pos]
        pos += 1
        value |= (b & 0x7f) << shift
        if not (b & 0x80):
            return value, pos
        shift += 7


def parse_mus(mus):
    ident, score_len, score_start, channels, sec_channels, instr_count, dummy = struct.unpack("<4sHHHHHH", mus[:16])
    if ident != b"MUS\x1a":
        raise SystemExit("not MUS data")
    pos = score_start
    end = score_start + score_len
    vols = [96] * 16
    pending_delay = 0
    events = []

    while pos < end:
        first_in_group = True
        while True:
            ev = mus[pos]
            pos += 1
            last = ev & 0x80
            typ = (ev >> 4) & 7
            ch = ev & 15

            delay = pending_delay if first_in_group else 0
            pending_delay = 0
            first_in_group = False

            if typ == 0:  # release note
                note = mus[pos] & 0x7f
                pos += 1
                if ch != 15:
                    events.append((delay, 2, ch % 5, note, 0))
                    delay = 0
            elif typ == 1:  # play note
                note_b = mus[pos]
                pos += 1
                note = note_b & 0x7f
                if note_b & 0x80:
                    vols[ch] = mus[pos] & 0x7f
                    pos += 1
                if ch == 15:
                    events.append((delay, 3, 0, note, vols[ch]))
                    delay = 0
                else:
                    events.append((delay, 1, ch % 5, note, vols[ch]))
                    delay = 0
            elif typ == 2:  # pitch wheel, ignored for first prototype
                pos += 1
            elif typ == 3:  # system event
                pos += 1
            elif typ == 4:  # controller
                ctrl = mus[pos]
                val = mus[pos + 1]
                pos += 2
                if ctrl == 7:
                    vols[ch] = val & 0x7f
            elif typ == 6:  # score end
                events.append((delay, 0, 0, 0, 0))
                return events, (score_len, channels, instr_count)
            else:
                raise SystemExit("bad MUS event type %d at %d" % (typ, pos - 1))

            if last:
                pending_delay, pos = read_var(mus, pos)
                break

    events.append((pending_delay, 0, 0, 0, 0))
    return events, (score_len, channels, instr_count)


def encode(events):
    out = bytearray()
    for delay, op, ch, note, vol in events:
        if delay > 65535:
            delay = 65535
        out.extend((delay & 0xff, (delay >> 8) & 0xff, op & 0xff))
        if op:
            out.extend((ch & 7, note & 0x7f, vol & 0x7f))
    return out


def carr(name, data, typ="unsigned char", perline=16):
    lines = ["const %s %s[%d] = {" % (typ, name, len(data))]
    for i in range(0, len(data), perline):
        lines.append("  " + ",".join(str(x) for x in data[i:i + perline]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    mus = read_lump(WAD, LUMP)
    events, meta = parse_mus(mus)
    stream = encode(events)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    guard = "MUSIC_GEN_H"
    with open(OUT + ".h", "w") as f:
        f.write("/* Auto-generated by tools/gen_music.py. Do not edit. */\n")
        f.write("#ifndef %s\n#define %s\n" % (guard, guard))
        f.write("extern const unsigned char music_e1m1_stream[%d];\n" % len(stream))
        f.write("extern const unsigned int music_e1m1_stream_len;\n")
        f.write("#endif\n")
    with open(OUT + ".c", "w") as f:
        f.write("/* Auto-generated by tools/gen_music.py. Do not edit. */\n")
        f.write("#include \"music_gen.h\"\n\n")
        f.write(carr("music_e1m1_stream", stream) + "\n")
        f.write("const unsigned int music_e1m1_stream_len = %d;\n" % len(stream))
    print("%s: mus=%dB events=%d stream=%dB channels=%d instr=%d" % (LUMP, len(mus), len(events), len(stream), meta[1], meta[2]))


if __name__ == "__main__":
    main()
