#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Compose the locally generated engine WAD's COLORMAP with the generated palette LUT."""
import argparse
from pathlib import Path
import re
import struct


def c_array(path, name):
    text = Path(path).read_text()
    match = re.search(r"\b" + re.escape(name) + r"\s*\[[^]]*\]\s*=\s*\{([^}]*)\}", text, re.S)
    if not match:
        raise ValueError(f"missing C array {name} in {path}")
    return bytes(int(x.strip(), 0) for x in match[1].split(',') if x.strip())


def compose(wad, lut):
    if wad[:4] != b'IWAD' or len(lut) != 256 or max(lut) > 15:
        raise ValueError('expected IWAD and 256-entry 16-color LUT')
    count, directory = struct.unpack_from('<II', wad, 4)
    for i in range(count):
        offset, size, name = struct.unpack_from('<II8s', wad, directory + 16*i)
        if name.rstrip(b'\0') == b'COLORMAP':
            maps = wad[offset:offset+size]
            if len(maps) != size or size < 32*256 or size % 256:
                raise ValueError('invalid COLORMAP size')
            combined = bytes(lut[c] for c in maps)
            # Fuzz reads already quantized framebuffer colors. Choose the most
            # frequent result of the original level-6 map for each color bin.
            # Exact equivalence is impossible once the original index is lost.
            fuzz = []
            for color in range(16):
                results = [lut[maps[6*256+c]] for c in range(256) if lut[c] == color]
                fuzz.append(max(range(16), key=results.count) if results else color)
            return combined, bytes(fuzz)
    raise ValueError('COLORMAP not found')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('wad_c')
    parser.add_argument('assets_c')
    parser.add_argument('output')
    args = parser.parse_args()
    combined, fuzz = compose(c_array(args.wad_c, 'doom_iwad'),
                             c_array(args.assets_c, 'asset_pal_lut'))
    lines = ['/* Generated by tools/gen_colormap16.py. */',
             '#ifndef COLORMAP16_GEN_H', '#define COLORMAP16_GEN_H']
    for name, values in [('gen_colormap16', combined), ('gen_fuzzmap16', fuzz)]:
        # R_LoadColorMap uses the engine bulk-copy routine on the 68000.
        lines.append(f'static const unsigned char {name}[{len(values)}] __attribute__((aligned(4))) = {{')
        lines.extend('  ' + ','.join(map(str, values[i:i+16])) + ','
                     for i in range(0, len(values), 16))
        lines.append('};')
    lines.append('#endif')
    Path(args.output).write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
